### ISSUE TITLE
Base URL to resolve URLs against

### ISSUE THREAD

**Issue by rictic** [WICG/import-maps#106]
Consider the import map:

```json
{
  "imports": {
    "foo": "./bar.js"
  }
}
```

What is `./bar.js` resolved relative to?

**Comment by rictic** [comment]
The document's base url is the natural answer, but if the import map was loaded from a standalone file rather than inlined in the document, it might make more sense to resolve relative to the import map's URL.

That's probably overly complex in the face of merged import maps though, as you'd have to keep track of which import map a mapping came from.

**Comment by domenic** [comment]
The intent is "the script's base URL", i.e. the document's base URL for inline scripts and the external URL for external scripts.

Merging shouldn't be that much more complicated, since merging will operate on the post-parsing/normalization data structure, and in those cases all URLs have already been made absolute.

Let's leave this open until we have a spec and tests for it.

**Comment by rictic** [comment]
Ah, good point, that makes sense.

> the external URL for external scripts

External scripts here meaning import maps that aren't inline in the document, i.e. `<script type="importmap" src="...">`

**Comment by domenic** [comment]
A spec and tests for this now exists! https://wicg.github.io/import-maps/#integration-prepare-a-script + https://github.com/web-platform-tests/wpt/tree/master/import-maps

**Comment by hiroshige-g** [comment]
Reopening this thread for a while to fix the spec.
I drafted a spec update but is blocked by https://github.com/WICG/import-maps/pull/143.
https://github.com/hiroshige-g/import-maps/commit/156eca8bc972fd852f52cb1edea15383de00c465
