### ISSUE TITLE
Clarify effect on stack introspection

### ISSUE THREAD

**Issue by mikesamuel** [WICG/import-maps#118]
It may be worth mentioning whether the same module specifier resolved to different files in different scopes should produce the same or different names in stack trace entries to avoid divergence that might complicate [proposal-error-stacks](https://github.com/tc39/proposal-error-stacks).

It may also be worth calling out in [Security and Privacy.md](https://github.com/WICG/import-maps/blob/master/Security%20and%20Privacy.md) whether backwards compatibility with [stack introspection code](https://gist.github.com/weaver/821554#file-stack2-js) is a goal.  IMO, it should not be due to the poor track record of stack introspection as a security mechanism and existing bypasses like Node's `vm` builtin.

**Comment by ljharb** [comment]
That proposal is for the format, not the contents, so it would be on a future proposal to specify how the contents interact with language features.

**Comment by domenic** [comment]
The intention is not to affect stacks, since stacks are based on source file URLs, which are distinct from module specifiers. I'm really unsure where the best place to include this information is, because I'm not sure where one might see spec text suggesting otherwise that needs clarification. Suggestions welcome.

My current thoughts are that probably when we merge into the HTML Standard, we'll need a basic introduction/example section (not as comprehensive as the explainer), and maybe we could put a note in there.
