### ISSUE TITLE
Should import map be applied to main module and workers main script?

### ISSUE THREAD

**Issue by bartlomieju** [WICG/import-maps#157]
During implementation of import maps for [Deno](https://github.com/denoland/deno) I believe I read that import maps shouldn't be applied to root script as well as workers root script, but now I can't find any mention about it now.

Example:
```js
// importmap.json
{
    "imports": {
         "https://deno.land/std/http/file_server.ts": "./foo/bar.ts"
     }
}
```

- main script:
```shellscript
$ deno --importmap importmap.json run https://deno.land/std/http/file_server.ts
// should script be loaded from original URL or should it use remapped './foo/bar.ts'?
```

- worker example:
```ts
// some_entry_point.ts
const worker = new Worker("https://deno.land/std/http/file_server.ts");
// should script be loaded from original URL or should it use remapped './foo/bar.ts'?
```

Could you clarify that @domenic? Thanks in advance.

**Comment by matthewp** [comment]
There's this issue about workers: https://github.com/WICG/import-maps/issues/2 if that helps.

**Comment by ljharb** [comment]
I would expect import maps to be applied to everything, including the root script.

**Comment by domenic** [comment]
This is largely a decision for deno to make. Does it take as input URLs, or module specifiers? URLs (which on the web show up in places like `<script src="url">` or `<link rel="modulepreload" href="url">`) don't get remapped by import maps; that's why we have future proposals for `import:` URLs and `import.meta.resolve()`. Module specifiers do get remapped.

I can tell you that on the web, `new Worker()` takes a URL, so it wouldn't get remapped.

Inside the Worker is a whole 'nother story; currently you cannot use import maps inside workers according to this spec, but that's a TODO as discussed in #2.
