### ISSUE TITLE
How do scopes match

### ISSUE THREAD

**Issue by domenic** [WICG/import-maps#73]
In particular substring matching is used by service worker and application manifest scopes, but this has been kind of weird and terrible, e.g. a scope of `https://google.com/maps` for that service worker also matches `https://google.com/mapsarecool`.

[Indeed, searching for "scope" in the app manifest issue tracker](https://github.com/w3c/manifest/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+scope) reveals a lot of weird issues. This is a subtle area.

I think import maps are not quite as fraught, as they are not as cross-cutting: the scope concept here governs a specific type of string translation, and doesn't need to interact with larger web platform concepts like service workers or origins or so on. But we should tread carefully.

/cc @mgiuca. Probably I should schedule a brain-dump session with you to see what aspects of the manifest experience I can draw on.

**Comment by domenic** [comment]
Related question came up while writing tests: if you use an empty string as your scope, what does that mean?

- Applies to all modules in the app, as if it were top-level `"imports"` instead of nested under `"scopes"`?
- Resolves the empty string against the base URL, i.e., use the base URL as the scope?
- Throw an exception and thus ignore the whole import map?
- Drop that particular scope, with a console warning?

Writing tests assuming URL resolution for now, but we should consciously decide an answer before closing this issue.

**Comment by mgiuca** [comment]
Happy to sync up over VC.

One thing about manifest is that the decision wasn't made in isolation, but specifically for consistency with Service Worker scope matching. Not exactly "compatibility" (since the two scope matching algorithms never overlap), but just consistency so users won't have to think about two different matching rules. It's possible that Import Maps are far enough removed from SW/Manifest that the consistency argument vanishes.

On the SW side, IIRC the rationale for the basic string prefix match was literally performance. Not having to split on '/' but instead being able to do a simple prefix match. Seems like premature optimization to me, and probably doesn't apply to imports.

Relevant discussion: w3c/ServiceWorker#1272

**Comment by marijnh** [comment]
In terms of performance, prefix match + a check of whether the match ends at a 'token boundary' (next to a slash or at the end of the string) should be plenty fast and less likely to trip people up

**Comment by guybedford** [comment]
@marijnh what sort of matching algorithm do you envisage for that?

**Comment by marijnh** [comment]
Something like `url.slice(0, prefix.length) == prefix && (url.length == prefix.length || url[prefix.length] == "/" || prefix.length && url[prefix.length - 1] == "/"`

**Comment by guybedford** [comment]
So checking each scope prefix, with the most-specific taking precedence I take it?

I previously considered avoiding the `O(scopeCount x bareImportSpecifierCount)` checks in https://github.com/domenic/import-maps/issues/39.

**Comment by marijnh** [comment]
You could still build a trie out of those to get pretty much linear matching time (you'd have to keep a stack of matching contexts in case contexts further down are rejected due to the token bounds check, but that's not hard or expensive).

But that feels a little like overkill. Maybe just keeping a sorted array of scopes, doing a binary search to find the position of the import specifier, and scanning up from there until a fully matching or mismatching scope is found is good enough, and simple to implement.

**Comment by guybedford** [comment]
> doing a binary search to find the position of the import specifier, and scanning up from there until a fully matching or mismatching scope is found is good enough, and simple to implement.

Seems good! I guess this applies regardless of how match priority / specificity is defined.

**Comment by domenic** [comment]
In https://github.com/WICG/import-maps/pull/115 @guybedford did some great work getting us started on answering these questions. In particular, it really crystalized some questions around trailing slashes and exact vs. prefix matching.

My tentative preference is that we treat any scopes which do not end in a trailing slash as exact matches, so that they only govern one URL. This enables cases like https://github.com/WICG/import-maps#wrapping-a-built-in-module . If we did prefix matching for those, or e.g. auto-appended a slash and then did prefix matching on those, the scope specified there could be "bypassed" by code located at e.g. `/js/als-wrapper.mjsbypass.mjs`. This isn't a huge deal, as it's all application author-controlled anyway, but it seems not great.

Thus, you need to use a trailing slash when specifying scopes that want to match more than exactly one URL. This also then avoids the issues like the ones discussed in the OP.

**Comment by guybedford** [comment]
Is supporting file scopes definitely a need? If so, the current approach seems great to me.

**Comment by domenic** [comment]
I'm not sure about "need", but it's certainly a use case that's come up, especially from folks who prioritize virtualization.

**Comment by littledan** [comment]
Single-resource scopes are pretty handy if you want to wrap a built-in module with a partial polyfill (e.g., for v2 features); otherwise, you would have to make sure that no other module URL shares the prefix. They are simpler than trailing slash scopes as well. It makes sense to me to include them as a basic concept.

**Comment by domenic** [comment]
This is fully specced and tested now, and seems to have settled. Let's close!
